// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMediaPath = `-- name: CreateMediaPath :one
INSERT INTO media_paths (path)
VALUES ($1) RETURNING id, path, created, updated
`

func (q *Queries) CreateMediaPath(ctx context.Context, path string) (MediaPath, error) {
	row := q.db.QueryRowContext(ctx, createMediaPath, path)
	var i MediaPath
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getMediaPathByID = `-- name: GetMediaPathByID :one
SELECT id, path, created, updated
FROM media_paths
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMediaPathByID(ctx context.Context, id uuid.UUID) (MediaPath, error) {
	row := q.db.QueryRowContext(ctx, getMediaPathByID, id)
	var i MediaPath
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getMediaPaths = `-- name: GetMediaPaths :many
SELECT id, path, created, updated
FROM media_paths
ORDER BY path
`

func (q *Queries) GetMediaPaths(ctx context.Context) ([]MediaPath, error) {
	rows, err := q.db.QueryContext(ctx, getMediaPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaPath
	for rows.Next() {
		var i MediaPath
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPictureByFilter = `-- name: GetPictureByFilter :one
SELECT id, path, ext, views, likes, rating, deviation, wins, losses, created, updated
FROM pictures
WHERE path LIKE '%' + $1 + '%' LIMIT 1
`

func (q *Queries) GetPictureByFilter(ctx context.Context, dollar_1 interface{}) (Picture, error) {
	row := q.db.QueryRowContext(ctx, getPictureByFilter, dollar_1)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Ext,
		&i.Views,
		&i.Likes,
		&i.Rating,
		&i.Deviation,
		&i.Wins,
		&i.Losses,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getPictureByID = `-- name: GetPictureByID :one
SELECT id, path, ext, views, likes, rating, deviation, wins, losses, created, updated
FROM pictures
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPictureByID(ctx context.Context, id uuid.UUID) (Picture, error) {
	row := q.db.QueryRowContext(ctx, getPictureByID, id)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Ext,
		&i.Views,
		&i.Likes,
		&i.Rating,
		&i.Deviation,
		&i.Wins,
		&i.Losses,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getPicturesByFilter = `-- name: GetPicturesByFilter :many
SELECT id, path, ext, views, likes, rating, deviation, wins, losses, created, updated
FROM pictures
WHERE path LIKE '%' + $1 + '%'
`

func (q *Queries) GetPicturesByFilter(ctx context.Context, dollar_1 interface{}) ([]Picture, error) {
	rows, err := q.db.QueryContext(ctx, getPicturesByFilter, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Picture
	for rows.Next() {
		var i Picture
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Ext,
			&i.Views,
			&i.Likes,
			&i.Rating,
			&i.Deviation,
			&i.Wins,
			&i.Losses,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
