// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeletePath struct {
	PathID int `json:"pathId"`
}

type NewPath struct {
	Path string `json:"path"`
}

type Path struct {
	ID   int    `json:"id"`
	Path string `json:"path"`
}
