version: '3.8'

services:

  backend:
    image: laosyne-backend:latest
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: changeme
      DB_NAME: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - C:\src:/src
      - P:\Lang:/Lang

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
