// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MediaPath struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

type NewMediaPath struct {
	Path string `json:"path"`
}
