// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"time"
)

type Path struct {
	ID      int64
	Path    string
	Created time.Time
	Updated time.Time
}

type Picture struct {
	ID        int64
	Path      string
	Ext       string
	Views     int32
	Likes     int32
	Rating    float64
	Deviation float64
	Wins      int32
	Losses    int32
	Created   time.Time
	Updated   time.Time
}
