// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type MediaPath struct {
	ID      uuid.UUID
	Path    string
	Created time.Time
	Updated time.Time
}

type Picture struct {
	ID        uuid.UUID
	Path      string
	Ext       string
	Views     int32
	Likes     int32
	Rating    float64
	Deviation float64
	Wins      int32
	Losses    int32
	Created   time.Time
	Updated   time.Time
}
