// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeletePath struct {
	PathID int `json:"pathId"`
}

type Match struct {
	PlayerOne *Picture `json:"playerOne"`
	PlayerTwo *Picture `json:"playerTwo"`
}

type MatchResult struct {
	WinnerID int `json:"winnerId"`
	LoserID  int `json:"loserId"`
}

type NewPath struct {
	Path string `json:"path"`
}

type Path struct {
	ID        int    `json:"id"`
	Path      string `json:"path"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Picture struct {
	ID        int     `json:"id"`
	Path      string  `json:"path"`
	Ext       string  `json:"ext"`
	Views     int     `json:"views"`
	Likes     int     `json:"likes"`
	Rating    float64 `json:"rating"`
	Deviation float64 `json:"deviation"`
	Wins      int     `json:"wins"`
	Losses    int     `json:"losses"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type SearchFilter struct {
	PathContains *string `json:"pathContains"`
}
