swagger: "2.0"
info:
  title: Swagger
  version: 0.1.0
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths: {}
definitions:
  path:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      path:
        type: string
        minLength: 3
      createdAt:
        type: string
      updatedAt:
        type: string
  picture:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      path:
        type: string
        minLength: 3
      ext:
        type: string
      views:
        type: integer
        format: int64
        readOnly: true
      likes:
        type: integer
        format: int64
        readOnly: true
      rating:
        type: integer
        format: float64
        readOnly: true
      deviation:
        type: integer
        format: float64
        readOnly: true
      wins:
        type: integer
        format: int64
        readOnly: true
      losses:
        type: integer
        format: int64
        readOnly: true
      createdAt:
        type: string
      updatedAt:
        type: string
