name: Ng

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          entrypoint: frontend
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM Install
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build
